### ISSUE TITLE
Non technical markers to build the model

### ISSUE THREAD

**Issue by aaiaueil** [Ipuch/bioNC#123] opened 2023-12-12 13:31 UTC
Would it be possible to use non technical markers to build the model? 

In the function biomecanical_model.py on line 451  we had to do the following modification to use some non technical markers for the model creation. We are not sure with @ANaaim that only technical marker marker should pass down to the model creation. Any thought about it ? Did we do something ''illegal'' 👮‍♂️ ?

```python
        # if markers.shape[1] != self.nb_markers_technical:
        #     raise ValueError(
        #         f"markers should have {self.nb_markers_technical} columns, "
        #         f"and should include the following markers: {self.marker_names_technical}"
        #     )

        # convert markers to Data
        from ..model_creation.generic_data import GenericData

        marker_data = GenericData(markers, self.marker_names)
```

**Comment by aaiaueil** [comment] 2023-12-12 13:34
If you think some modifications should be done we can take care of it! For now an ugly solution has been implemented to bypass this issue but I'm trying to overcome my ugly code phase

**Comment by Ipuch** [comment] 2023-12-12 13:56
Removing raise is globally a bad idea, because I excluded cases where I know my code is not safe to be used. I prevent the user to do something wrong, and also for the developer removing a raise, is a huge responsibility.

Why can set your marker as an anatomical and a technical marker ? Would it work for you ?
Nothing prevents you to define a marker as technical and as anatomical at the same time.

**Comment by ANaaim** [comment] 2023-12-12 14:44
Because if the marker is labeled as a technical marker it will be used later for the optimisation process.

**Comment by Ipuch** [comment] 2023-12-12 15:02
Does it work if you set istechnical to false for the given marker after having built the model ?

**Comment by ANaaim** [comment] 2023-12-12 15:08
Ok, did not think that was possible ==> we will have a look at it.

**Comment by Ipuch** [comment] 2023-12-12 15:21
My thoughts got clearer:

- In which context do you used this function Q_from_markers? Is it absolutely useful ?

- This function Q_from_markers estimates Qi of segment from experimental markers, so we cannot remove a marker. As it needs a specific set of markers to be evaluated...

- The best way would be to be a new model not relaying on that marker... 
- Another avenue (not sure of what it cost in terms of implementation) would be to reset all the experimental functions of all segments excluding the marker you want.

- Can you provide the full error message that initially came out ?

**Comment by aaiaueil** [comment] 2023-12-12 16:13
- I used Q_from_markers to generate Q_initialize for the optimisation. I'd say it's rather useful here.
````python
Q_initialize = model_init.Q_from_markers(marker_xp_initialize[:, :, 0:nb_frames])
````
- see the error message attached. right_heel is a marker present in my c3d file but I did not put it as a technical marker (already got 2 markers as technical markers and I don't want to weight more the foot than other segments). right_heel has been defined as an anatomical marker in the RFOOT segment:
- 
````python
    model["LFOOT"].add_marker(
        MarkerTemplate(name="left_heel", parent_name="LFOOT", is_technical=False, is_anatomical=True)
    )
````
![image](https://github.com/Ipuch/bioNC/assets/117843307/427af71c-6615-48ce-8925-f7fd29fb662c)

**Comment by Ipuch** [comment] 2023-12-12 16:30
Ok so the problem is later... you should implement weights in inverse kinematics class add an extra argument that sets the weights to 1 to every marker if no weights are given, or take the user define weight list.

And yes, you cannot evaluate Qi through markers if you don't give the markers that has been used to build the model, that's the expected behavior

Normally, Q_from_markers is automatically called when you provide no Q_init to simplify the user interface.

By the way, Are you sure you can call this function with all frames at the time ?

**Comment by Ipuch** [comment] 2024-03-15 13:59
Can I close the issue ?

**Comment by Ipuch** [comment] 2024-03-25 18:09
up ?

**Closed** 2024-04-24 19:48 UTC
Labels: help wanted
